### ISSUE TITLE
Arguments.argString cannot be quoted with "`"

### ISSUE THREAD

**Issue by Librazy** [NyaaCat/NyaaCore#12]

**Comment by RecursiveG** [comment]
You may want to quote whole `key:value` pair with `` ` ``
see 88460ace70688eb4fd2c5befbc87ac2a2c9c772b

**Comment by Librazy** [comment]
A bit weird though……
所以说支持一下这种写法嘛
```
/rpgitem power item command:`say hi`
```

**Comment by Librazy** [comment]
And what if I simply need a argument that contains a `:`?
/rpitem description item add `Foo: bar`
`Foo: bar` should be parsed as a whole string "Foo: bar"
and Foo:`Foo bars` is a k-v pair

**Comment by RecursiveG** [comment]
Then just call `nextString()` as shown [here](https://github.com/NyaaCat/NyaaCore/commit/88460ace70688eb4fd2c5befbc87ac2a2c9c772b#diff-bfb5836e2676035f26c276b907e72eedR23).

Another demo:
``` java
String cmd = "`foo: bar` foo:foo:bar";
CommandReceiver.Arguments arg = CommandReceiver.Arguments.parse(cmd.split(" "));
arg.nextString(); // Returns "foo: bar"
arg.argString("foo"); // Returns "foo:bar"
```

**Comment by Librazy** [comment]
With key:\`value\` enabled, I can use syntax like 
```
/rpgitem power item command cooldown:10 command:`say hi`
/heh search name:`Wood sword`
```
and I can make tab completion like 
```
/rpgitem power item command
(tab)
/rpgitem power item command cooldown:`` mouse:`` command:``
```

instead of
```
/rpgitem power item command `cooldown:` ` mouse:` `command:`
```
which leads to lot of confusing.
