### ISSUE TITLE
Freeze methods for every version

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/NyaaCore#21]
Rel: #15 

Do not break API in minor and patch versions like mojang.

If you are going to break any API in this library, bump the main version and recheck all plugins depending on it.

**Comment by Librazy** [comment]
Actually NC4.1 didn't *seems to* break any API, it have all the method from NC4.0. But some API's requirements and sematice changed: [don't allow `null` column](https://github.com/NyaaCat/NyaaCore/commit/755895a7f94f90c96aa9ec00720f29f1840583b7#diff-e45ed43d4ce0204543b840cd92e1fe23L48) and [don't allow `UUID` column](https://github.com/NyaaCat/NyaaCore/commit/d5f4a39ad4d4a4a9b378cb7025f6d6297bb8902d#diff-e45ed43d4ce0204543b840cd92e1fe23L46). So bugs happened on exactly same API that works before.
