### ISSUE TITLE
NyaaCore not loading/being recognized? Spigot 1.12

### ISSUE THREAD

**Issue by KindaRed** [NyaaCat/NyaaCore#22]
Hello, I recently found your RPGItems Reloaded plugin and I installed it, after it not working I realized there was a dependency, NyaaCore... After installing NyaaCore still no luck and this is all that I could find in the console. Here is the log.

https://hastebin.com/umakuqexot.sql

**Comment by phoenixlzx** [comment]
Please use RPGitem 3.5

3.6 depends on NyaaCore and NyaaCore depends on LangUtils - so install LangUtils if you insist with 3.6.
https://github.com/MascusJeoraly/LanguageUtils/releases
