### ISSUE TITLE
Missing Dependancy? Does not Exist?

### ISSUE THREAD

**Issue by Flugal** [NyaaCat/NyaaCore#23]
02.12 03:32:36 [Server] ERROR Could not load 'plugins/NyaaCore-v4.1.69-mc1.12.jar' in folder 'plugins' 02.12 03:32:36 [Server] INFO org.bukkit.plugin.UnknownDependencyException: LangUtils 02.12 03:32:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:216) [spigot131.jar:git-Spigot-7754231-94b0980] 02.12 03:32:36 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:308) [spigot131.jar:git-Spigot-7754231-94b0980] 02.12 03:32:36 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot131.jar:git-Spigot-7754231-94b0980] 02.12 03:32:36 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot131.jar:git-Spigot-7754231-94b0980] 02.12 03:32:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121] 02.12 03:32:36 [Server] ERROR Could not load 'plugins/rpgitem-reloaded-1.12-v.277.jar' in folder 'plugins' 02.12 03:32:36 [Server] INFO org.bukkit.plugin.UnknownDependencyException: NyaaCore 02.12 03:32:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:216) [spigot131.jar:git-Spigot-7754231-94b0980] 02.12 03:32:36 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:308) [spigot131.jar:git-Spigot-7754231-94b0980] 02.12 03:32:36 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot131.jar:git-Spigot-7754231-94b0980] 02.12 03:32:36 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot131.jar:git-Spigot-7754231-94b0980] 02.12 03:32:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

What is "LangUtils" and where can I find it?

**Comment by RecursiveG** [comment]
Yes, LangUtils is one of the dependencies of NyaaCore.
You can download from [their official Spigot page](https://www.spigotmc.org/resources/1-7-x-1-12-language-utils.8859/)
NyaaCore also depends on Vault, so you will want to install that, too.
