### ISSUE TITLE
Cant Build NyaaCore.

### ISSUE THREAD

**Issue by freaki2010** [NyaaCat/NyaaCore#37]
Good morning,
since i did not find any current builds on jenkins for the latest changes to the plugin, i wanted to build them myself. I was able to build all necessary plugins & RPGItems except NyaaCore...
The error message looks like this:
https://haste.gafert.org/imoxamazuk.coffeescript

I wish you a Merry Christmas and thank you for your help!

**Comment by RecursiveG** [comment]
Build for mc1.15.1 is up. The mentioned error in your log is fixed.
However, no tests were performed yet. Please use with caution and do backup.
